trigger:
- master

pool:
  vmImage: 'Ubuntu-20.04'

variables:
  terraformVersion: '0.14.0'
  environment: 'dev'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '$(terraformVersion)'

- task: TerraformTask@0
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    command: 'init'

- task: TerraformTask@0
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    command: 'plan'
    commandOptions: '-var "environment=$(environment)"'

- task: TerraformTask@0
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    command: 'apply'
    commandOptions: '-auto-approve -var "environment=$(environment)"'
